// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.2032
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Mono Web Services Description Language Utility
//
namespace Spring.Ws.Samples.Airline.Client.CSharp {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="AirlinePort", Namespace="http://www.springframework.org/spring-ws/samples/airline/definitions")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public class AirlineService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public AirlineService() {
            this.Url = "http://localhost:8080/airline/Airline";
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.springframework.org/spring-ws/samples/airline/GetFlights", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArray(ElementName="GetFlightsResponse", Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")]
        [return: System.Xml.Serialization.XmlArrayItem(ElementName="flight", IsNullable=false)]
        public Flight[] GetFlights([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")] MessageGetFlightsRequest GetFlightsRequest) {
            object[] results = this.Invoke("GetFlights", new object[] {
                GetFlightsRequest});
            return ((Flight[])(results[0]));
        }
        
        public System.IAsyncResult BeginGetFlights(MessageGetFlightsRequest GetFlightsRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetFlights", new object[] {
                GetFlightsRequest}, callback, asyncState);
        }
        
        public Flight[] EndGetFlights(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Flight[])(results[0]));
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.springframework.org/spring-ws/samples/airline/BookFlight", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("BookFlightResponse", Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")]
        public Ticket BookFlight([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")] MessageBookFlightRequest BookFlightRequest) {
            object[] results = this.Invoke("BookFlight", new object[] {
                BookFlightRequest});
            return ((Ticket)(results[0]));
        }
        
        public System.IAsyncResult BeginBookFlight(MessageBookFlightRequest BookFlightRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BookFlight", new object[] {
                BookFlightRequest}, callback, asyncState);
        }
        
        public Ticket EndBookFlight(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Ticket)(results[0]));
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.springframework.org/spring-ws/samples/airline/GetFrequentFlyerMileage", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetFrequentFlyerMileageResponse", Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")]
        public int GetFrequentFlyerMileage([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")] object GetFrequentFlyerMileageRequest) {
            object[] results = this.Invoke("GetFrequentFlyerMileage", new object[] {
                GetFrequentFlyerMileageRequest});
            return ((int)(results[0]));
        }
        
        public System.IAsyncResult BeginGetFrequentFlyerMileage(object GetFrequentFlyerMileageRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetFrequentFlyerMileage", new object[] {
                GetFrequentFlyerMileageRequest}, callback, asyncState);
        }
        
        public int EndGetFrequentFlyerMileage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")]
    [System.Xml.Serialization.XmlRootAttribute("GetFlightsRequest", Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")]
    public class MessageGetFlightsRequest {
        
        /// <remarks/>
        public string from;
        
        /// <remarks/>
        public string to;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime departureDate;
        
        /// <remarks/>
        public ServiceClass serviceClass;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool serviceClassSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")]
    public enum ServiceClass {
        
        /// <remarks/>
        economy,
        
        /// <remarks/>
        business,
        
        /// <remarks/>
        first,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")]
    public class Flight {
        
        /// <remarks/>
        public string number;
        
        /// <remarks/>
        public System.DateTime departureTime;
        
        /// <remarks/>
        public Airport from;
        
        /// <remarks/>
        public System.DateTime arrivalTime;
        
        /// <remarks/>
        public Airport to;
        
        /// <remarks/>
        public ServiceClass serviceClass;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")]
    public class Airport {
        
        /// <remarks/>
        public string code;
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string city;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")]
    [System.Xml.Serialization.XmlRootAttribute("BookFlightRequest", Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")]
    public class MessageBookFlightRequest {
        
        /// <remarks/>
        public string flightNumber;
        
        /// <remarks/>
        public System.DateTime departureTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="passenger", Type=typeof(Name), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="username", Type=typeof(string), IsNullable=false)]
        public object[] passengers;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")]
    public class Name {
        
        /// <remarks/>
        public string first;
        
        /// <remarks/>
        public string last;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")]
    [System.Xml.Serialization.XmlRootAttribute("BookFlightResponse", Namespace="http://www.springframework.org/spring-ws/samples/airline/schemas")]
    public class Ticket {
        
        /// <remarks/>
        public long id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime issueDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="passenger", IsNullable=false)]
        public Name[] passengers;
        
        /// <remarks/>
        public Flight flight;
    }
}
