
package org.springframework.ws.samples.airline.client.jws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AirlinePortType", targetNamespace = "http://www.springframework.org/spring-ws/samples/airline/definitions")
@SOAPBinding(parameterStyle = ParameterStyle.BARE)
public interface AirlinePortType {


    /**
     * 
     * @param body
     * @return
     *     returns org.springframework.ws.samples.airline.client.jws.GetFlightsResponse
     */
    @WebMethod(operationName = "GetFlights", action = "http://www.springframework.org/spring-ws/samples/airline/GetFlights")
    @WebResult(name = "GetFlightsResponse", targetNamespace = "http://www.springframework.org/spring-ws/samples/airline/schemas", partName = "body")
    public GetFlightsResponse getFlights(
        @WebParam(name = "GetFlightsRequest", targetNamespace = "http://www.springframework.org/spring-ws/samples/airline/schemas", partName = "body")
        GetFlightsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns org.springframework.ws.samples.airline.client.jws.Ticket
     */
    @WebMethod(operationName = "BookFlight", action = "http://www.springframework.org/spring-ws/samples/airline/BookFlight")
    @WebResult(name = "BookFlightResponse", targetNamespace = "http://www.springframework.org/spring-ws/samples/airline/schemas", partName = "body")
    public Ticket bookFlight(
        @WebParam(name = "BookFlightRequest", targetNamespace = "http://www.springframework.org/spring-ws/samples/airline/schemas", partName = "body")
        BookFlightRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetFrequentFlyerMileage", action = "http://www.springframework.org/spring-ws/samples/airline/GetFrequentFlyerMileage")
    @WebResult(name = "GetFrequentFlyerMileageResponse", targetNamespace = "http://www.springframework.org/spring-ws/samples/airline/schemas", partName = "body")
    public int getFrequentFlyerMileage(
        @WebParam(name = "GetFrequentFlyerMileageRequest", targetNamespace = "http://www.springframework.org/spring-ws/samples/airline/schemas", partName = "body")
        Object body);

}
