
/*
 * Copyright 2006 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.ws.samples.airline.client.jws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "AirlineService", targetNamespace = "http://www.springframework.org/spring-ws/samples/airline/definitions", wsdlLocation = "http://localhost:8080/airline/airline.wsdl")
public class AirlineService
    extends Service
{

    private final static URL AIRLINESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/airline/airline.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        AIRLINESERVICE_WSDL_LOCATION = url;
    }

    public AirlineService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AirlineService() {
        super(AIRLINESERVICE_WSDL_LOCATION, new QName("http://www.springframework.org/spring-ws/samples/airline/definitions", "AirlineService"));
    }

    /**
     * 
     * @return
     *     returns AirlinePortType
     */
    @WebEndpoint(name = "AirlinePort")
    public AirlinePortType getAirlinePort() {
        return (AirlinePortType)super.getPort(new QName("http://www.springframework.org/spring-ws/samples/airline/definitions", "AirlinePort"), AirlinePortType.class);
    }

}
