CREATE DATABASE airline;

GRANT ALL ON DATABASE airline TO airline;

CREATE TABLE CUSTOMER (
	 ID BIGSERIAL NOT NULL PRIMARY KEY,
	 FIRST_NAME VARCHAR(30),
	 LAST_NAME VARCHAR(30)
);

CREATE TABLE AIRPORT (
	CODE CHAR(3) NOT NULL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	CITY VARCHAR(20) NOT NULL
);

CREATE TABLE FLIGHT (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	NUMBER VARCHAR(20) NOT NULL,
	DEPARTURE_TIME DATE NOT NULL,
	DEPARTURE_AIRPORT CHAR(3) NOT NULL REFERENCES AIRPORT(CODE),
	ARRIVAL_TIME DATE NOT NULL,
	ARRIVAL_AIRPORT CHAR(3) NOT NULL REFERENCES AIRPORT(CODE),
	SERVICE_CLASS VARCHAR(10) NOT NULL
);

CREATE TABLE TICKET (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	ISSUE_DATE DATE NOT NULL,
	CUSTOMER_ID INT NOT NULL REFERENCES CUSTOMER(ID),
	FLIGHT_ID INT NOT NULL REFERENCES FLIGHT(ID)
);