version: 2
jobs:
   test:
     docker:
       - image: circleci/openjdk:8u141
     steps:
            - checkout
            - run: ./mvnw -Pdistribute,snapshot,docs clean test
   test_next:
     docker:
       - image: circleci/openjdk:8u141
     steps:
            - checkout
            - run: ./mvnw -Pspringnext clean test
   deploy:
     docker:
       - image: circleci/openjdk:8u141
     steps:
            - checkout
            - run: ./deploy.bash

workflows:
  version: 2
  test_and_deploy:
    - test
    - test_next
    - deploy:
      requires:
        - test
        - test_next

general:
  branches:
    ignore:
      - gh-pages # list of branches to ignore

dependencies:
  cache_directories:
    - "~/.m2"
