= Contributing to Spring Web Services

Spring Web Services is released under the Apache 2.0 license. If you would like to contribute
something, or simply want to hack on the code this document should help you get started.

== Code of Conduct
This project adheres to the Contributor Covenant link:CODE_OF_CONDUCT.adoc[code of
conduct]. By participating, you  are expected to uphold this code. Please report
unacceptable behavior to spring-code-of-conduct@pivotal.io.

== Using JIRA issues
We use JIRA issues to track bugs and enhancements. If you have a general usage question
please ask on https://stackoverflow.com[Stack Overflow]. The Spring Web Services team and the
broader community monitor the https://stackoverflow.com/tags/spring-ws[`spring-ws`]
tag.

If you are reporting a bug, please help to speed up problem diagnosis by providing as much
information as possible. Submitting a github-hosted sample project replicating the problem helps.

== Sign the Contributor License Agreement
If you have not previously done so, please fill out and
submit the https://cla.pivotal.io/sign/spring[Contributor License Agreement].

Signing the contributor's agreement does not grant anyone commit rights to the main
repository, but it does mean that we can accept your contributions, and you will get an
author credit if we do.  Active contributors might be asked to join the core team, and
given the ability to merge pull requests.

== Code Conventions and Housekeeping
None of these are essential for a pull request, but they help.  They can also be
added after the original pull request but before a merge.

* Use the Spring Framework code format conventions.
* Make sure all new `.java` files to have a simple Javadoc class comment with at least an
  `@author` tag identifying you, and preferably at least a paragraph on what the class is
  for.
* Add the ASF license header comment to all new `.java` files (copy from existing files
  in the project)
* Add yourself as an `@author` to the `.java` files that you modify substantially (more
  than cosmetic changes).
* Add some Javadocs.
* A few unit tests would help a lot as well -- someone has to do it.
* If no-one else is using your branch, please rebase it against the current master (or
  other target branch in the main project).
* When writing a commit message please follow http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[these conventions].

=== Building from source
This project includes the Gradle wrapper, meaning you don't have to install any CLI tools to compile. Simply clone it and do this:

==== Default build
The project can be built from the root directory using the standard gradle wrapper command:

----
$ ./gradlew clean build
----

If you are rebuilding often, you might also want to skip the tests until you are ready
to submit a pull request:

----
$ ./gradlew clean build -x test
----
