= Spring Web Services

Spring Web Services is a product of the Spring community focused on creating
document-driven Web services. Spring Web Services aims to facilitate
contract-first SOAP service development, allowing for the creation of flexible
web services using one of the many ways to manipulate XML payloads.

== Project Status

To see project status, https://github.com/spring-projects/spring-ws#project-status[visit this on master branch].

== Installation

Releases of Spring Web Services are available for download from Maven Central,
as well as our own repository, http://repo.spring.io/release[http://repo.springsource.org/release].

Please visit https://projects.spring.io/spring-ws to get the right Maven/Gradle settings for your selected version.

== Building Spring Web Services

. Run `mvn clean package`

This will generate the artifacts.

You can also import the project into your IDE.

== Code of Conduct

This project adheres to the Contributor Covenant link:CODE_OF_CONDUCT.adoc[code of conduct].
By participating, you  are expected to uphold this code. Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.

= Spring Web Services Project Site

You can find the documentation, issue management, support, samples, and guides for using Spring Web Services at http://projects.spring.io/spring-ws/

== Documentation

See the current http://docs.spring.io/spring-ws/docs/current/api/[Javadoc] and http://docs.spring.io/spring-ws/docs/current/reference/htmlsingle/[reference docs].

== Issue Tracking

Spring Web Services uses https://jira.spring.io/browse/SWS[JIRA] for issue tracking purposes

== License

Spring Web Services is http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 licensed].