= Spring Web Services

image:https://circleci.com/gh/spring-projects/spring-ws.svg?style=svg["CircleCI", link="https://circleci.com/gh/spring-projects/spring-ws"]

Spring Web Services is a product of the Spring community focused on creating
document-driven Web services. Spring Web Services aims to facilitate
contract-first SOAP service development, allowing for the creation of flexible
web services using one of the many ways to manipulate XML payloads.

== Installation

Releases of Spring Web Services are available for download from Maven Central,
as well as our own repository, http://repo.spring.io/release[http://repo.springsource.org/release].

Please visit https://projects.spring.io/spring-ws to get the right Maven/Gradle settings for your selected version.

== Building from Source

Spring Web Services uses a http://gradle.org[Gradle]-based build system. In
the instructions below, http://vimeo.com/34436402[`./gradlew`] is invoked
from the root of the source tree and serves as a cross-platform, self-contained
bootstrap mechanism for the build. The only prerequisites are
http://help.github.com/set-up-git-redirect[Git] and JDK 1.7+.

=== check out sources

`git clone git://github.com/spring-projects/spring-ws.git`

=== compile and test, build all jars, distribution zips and docs

`./gradlew build`

=== install all spring-* jars into your local Maven cache

`./gradlew install`

… and discover more commands with `./gradlew tasks`. See also the https://github.com/spring-projects/spring-framework/wiki/Gradle-build-and-release-FAQ[Gradle build and release FAQ].

== Documentation

See the current http://docs.spring.io/spring-ws/docs/current/api/[Javadoc] and http://docs.spring.io/spring-ws/docs/current/reference/htmlsingle/[reference docs].

== Issue Tracking

Spring Web Services uses https://jira.spring.io/browse/SWS[JIRA] for issue tracking purposes

== License

Spring Web Services is http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 licensed].