// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.2032
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Mono Web Services Description Language Utility
//

/// <remarks/>
[System.Web.Services.WebServiceBinding(Name="AirlinePort", Namespace="http://www.springframework.org/spring-ws/samples/airline")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public class AirlineService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    public AirlineService() {
        this.Url = "http://localhost:8080/airline/Airline";
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.springframework.org/spring-ws/samples/airline/GetFlights", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlArray(ElementName="GetFlightsResponse", Namespace="http://www.springframework.org/spring-ws/samples/airline")]
    [return: System.Xml.Serialization.XmlArrayItem(ElementName="flight", IsNullable=false)]
    public Flight[] GetFlights([System.Xml.Serialization.XmlElement(Namespace="http://www.springframework.org/spring-ws/samples/airline")] MessageGetFlightsRequest GetFlightsRequest) {
        object[] results = this.Invoke("GetFlights", new object[] {
            GetFlightsRequest});
        return ((Flight[])(results[0]));
    }
    
    public System.IAsyncResult BeginGetFlights(MessageGetFlightsRequest GetFlightsRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetFlights", new object[] {
            GetFlightsRequest}, callback, asyncState);
    }
    
    public Flight[] EndGetFlights(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Flight[])(results[0]));
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.springframework.org/spring-ws/samples/airline/BookFlight", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElement("BookFlightResponse", Namespace="http://www.springframework.org/spring-ws/samples/airline")]
    public Ticket BookFlight([System.Xml.Serialization.XmlElement(Namespace="http://www.springframework.org/spring-ws/samples/airline")] MessageBookFlightRequest BookFlightRequest) {
        object[] results = this.Invoke("BookFlight", new object[] {
            BookFlightRequest});
        return ((Ticket)(results[0]));
    }
    
    public System.IAsyncResult BeginBookFlight(MessageBookFlightRequest BookFlightRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("BookFlight", new object[] {
            BookFlightRequest}, callback, asyncState);
    }
    
    public Ticket EndBookFlight(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Ticket)(results[0]));
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlType(Namespace="http://www.springframework.org/spring-ws/samples/airline")]
[System.Xml.Serialization.XmlRoot("GetFlightsRequest", Namespace="http://www.springframework.org/spring-ws/samples/airline")]
public class MessageGetFlightsRequest {
    
    /// <remarks/>
    public string flightNumber;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElement(DataType="date")]
    public System.DateTime startOfPeriod;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnore()]
    public bool startOfPeriodSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElement(DataType="date")]
    public System.DateTime endOfPeriod;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnore()]
    public bool endOfPeriodSpecified;
}

/// <remarks/>
[System.Xml.Serialization.XmlType(Namespace="http://www.springframework.org/spring-ws/samples/airline")]
public class Flight {
    
    /// <remarks/>
    public string number;
    
    /// <remarks/>
    public System.DateTime departureTime;
    
    /// <remarks/>
    public Airport departureAirport;
    
    /// <remarks/>
    public System.DateTime arrivalTime;
    
    /// <remarks/>
    public Airport arrivalAirport;
    
    /// <remarks/>
    public ServiceClass serviceClass;
}

/// <remarks/>
[System.Xml.Serialization.XmlType(Namespace="http://www.springframework.org/spring-ws/samples/airline")]
public class Airport {
    
    /// <remarks/>
    public string code;
    
    /// <remarks/>
    public string name;
    
    /// <remarks/>
    public string city;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.springframework.org/spring-ws/samples/airline")]
public enum ServiceClass {
    
    /// <remarks/>
    economy,
    
    /// <remarks/>
    business,
    
    /// <remarks/>
    first,
}

/// <remarks/>
[System.Xml.Serialization.XmlType(Namespace="http://www.springframework.org/spring-ws/samples/airline")]
[System.Xml.Serialization.XmlRoot("BookFlightRequest", Namespace="http://www.springframework.org/spring-ws/samples/airline")]
public class MessageBookFlightRequest {
    
    /// <remarks/>
    public string flightNumber;
    
    /// <remarks/>
    public long customerId;
}

/// <remarks/>
[System.Xml.Serialization.XmlType(Namespace="http://www.springframework.org/spring-ws/samples/airline")]
[System.Xml.Serialization.XmlRoot("BookFlightResponse", Namespace="http://www.springframework.org/spring-ws/samples/airline")]
public class Ticket {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElement(DataType="date")]
    public System.DateTime issueDate;
    
    /// <remarks/>
    public Customer customer;
    
    /// <remarks/>
    public Flight flight;
}

/// <remarks/>
[System.Xml.Serialization.XmlType(Namespace="http://www.springframework.org/spring-ws/samples/airline")]
public class Customer {
    
    /// <remarks/>
    public long id;
    
    /// <remarks/>
    public Name name;
}

/// <remarks/>
[System.Xml.Serialization.XmlType(Namespace="http://www.springframework.org/spring-ws/samples/airline")]
public class Name {
    
    /// <remarks/>
    public string first;
    
    /// <remarks/>
    public string last;
}

