:toclevels: 10

[[common]]
= Shared components

This chapter explores the components that are shared between client- and server-side Spring-WS development.
These interfaces and classes represent the building blocks of Spring-WS, so you need to understand what they do, even if you do not use them directly.

[[web-service-null-safety]]
== Null Safety
Spring-WS is annotated with https://jspecify.dev/docs/start-here/[JSpecify] annotations to declare the nullability of its API.
To learn more about JSpecify, its https://jspecify.dev/docs/user-guide/[user guide] is recommended reading.

The primary goal of declaring the nullability of the API is to prevent a `NullPointerException` from being thrown at runtime.
This is achieved through build-time checks that are available with both Java and Kotlin.
Performing the checks with Java requires some tooling such as https://github.com/uber/NullAway[NullAway] or an IDE that supports JSpecify annotations such as IntelliJ IDEA.
The checks are available automatically with Kotlin which translates the JSpecify annotations into Kotlin's null safety.

To learn more about null safety with Spring, refer to the {spring-framework-docs}/core/null-safety.html[Spring Framework reference documentation].

[[web-service-messages]]
== Web Service Messages

This section describes the messages and message factories that Spring-WS uses.

[[web-service-message]]
=== `WebServiceMessage`

One of the core interfaces of Spring-WS is the `WebServiceMessage`.
This interface represents a protocol-agnostic XML message.
The interface contains methods that provide access to the payload of the message, in the form of a `javax.xml.transform.Source` or a `javax.xml.transform.Result`.
`Source` and `Result` are tagging interfaces that represent an abstraction over XML input and output.
Concrete implementations wrap various XML representations, as indicated in the following table:

[cols="2", options="header"]
|===
| Source or Result implementation
| Wrapped XML representation

| `javax.xml.transform.dom.DOMSource`
| `org.w3c.dom.Node`

| `javax.xml.transform.dom.DOMResult`
| `org.w3c.dom.Node`

| `javax.xml.transform.sax.SAXSource`
| `org.xml.sax.InputSource` and `org.xml.sax.XMLReader`

| `javax.xml.transform.sax.SAXResult`
| `org.xml.sax.ContentHandler`

| `javax.xml.transform.stream.StreamSource`
| `java.io.File`, `java.io.InputStream`, or `java.io.Reader`

| `javax.xml.transform.stream.StreamResult`
| `java.io.File`, `java.io.OutputStream`, or `java.io.Writer`
|===

In addition to reading from and writing to the payload, a web service message can write itself to an output stream.

[[soap-message]]
=== `SoapMessage`

`SoapMessage` is a subclass of `WebServiceMessage`.
It contains SOAP-specific methods, such as getting SOAP Headers, SOAP Faults, and so on.
Generally, your code should not be dependent on `SoapMessage`, because the content of the SOAP Body (the payload of the message) can be obtained by using `getPayloadSource()` and `getPayloadResult()` in the `WebServiceMessage`.
Only when it is necessary to perform SOAP-specific actions (such as adding a header, getting an attachment, and so on) should you need to cast `WebServiceMessage` to `SoapMessage`.

[[message-factories]]
=== Message Factories

Concrete message implementations are created by a `WebServiceMessageFactory`.
This factory can create an empty message or read a message from an input stream.
There are two concrete implementations of `WebServiceMessageFactory`.
One is based on SAAJ, the SOAP with Attachments API for Java.
The other is based on Axis 2’s AXIOM (AXis Object Model).

==== `SaajSoapMessageFactory`

The `SaajSoapMessageFactory` uses the SOAP with Attachments API for Java (SAAJ) to create `SoapMessage` implementations.
SAAJ is part of J2EE 1.4, so it should be supported under most modern application servers.
Here is an overview of the SAAJ versions supplied by common application servers:

[cols="2", options="header"]
|===
| Application Server
| SAAJ Version

| BEA WebLogic 8
| 1.1

| BEA WebLogic 9
| 1.1/1.2^1^

| IBM WebSphere 6
| 1.2

| SUN Glassfish 1
| 1.3

2+|^1^Weblogic 9 has a known bug in the SAAJ 1.2 implementation: it implements all the 1.2 interfaces but throws an `UnsupportedOperationException` when called.
Spring-WS has a workaround: It uses SAAJ 1.1 when operating on WebLogic 9.
|===

Additionally, Java SE 6 includes SAAJ 1.3.
You can wire up a `SaajSoapMessageFactory` as follows:

====
[source,xml]
----
<bean id="messageFactory" class="org.springframework.ws.soap.saaj.SaajSoapMessageFactory" />
----
====

[NOTE]
====
SAAJ is based on DOM, the Document Object Model.
This means that all SOAP messages are stored in memory.
For larger SOAP messages, this may not be performant.
In that case, the `AxiomSoapMessageFactory` might be more applicable.
====

==== `AxiomSoapMessageFactory`

The `AxiomSoapMessageFactory` uses the AXis 2 Object Model (AXIOM) to create `SoapMessage` implementations.
AXIOM is based on StAX, the Streaming API for XML.
StAX provides a pull-based mechanism for reading XML messages, which can be more efficient for larger messages.

To increase reading performance on the `AxiomSoapMessageFactory`, you can set the `payloadCaching` property to false (default is true).
Doing so causes the contents of the SOAP body to be read directly from the socket stream.
When this setting is enabled, the payload can be read only once.
This means that you have to make sure that any pre-processing (logging or other work) of the message does not consume it.

You can use the `AxiomSoapMessageFactory` as follows:

====
[source,xml]
----
<bean id="messageFactory" class="org.springframework.ws.soap.axiom.AxiomSoapMessageFactory">
    <property name="payloadCaching" value="true"/>
</bean>
----
====

In addition to payload caching, AXIOM supports full streaming messages, as defined in the `StreamingWebServiceMessage`.
This means that you can directly set the payload on the response message, rather than writing it to a DOM tree or buffer.

Full streaming for AXIOM is used when a handler method returns a JAXB2-supported object.
It automatically sets this marshalled object into the response message and writes it out to the outgoing socket stream when the response is going out.

For more information about full streaming, see {spring-ws-api}/stream/StreamingWebServiceMessage.html[`StreamingWebServiceMessage`] and {spring-ws-api}/stream/StreamingPayload.html[`StreamingPayload`].

[[soap_11_or_12]]
==== SOAP 1.1 or 1.2

Both the `SaajSoapMessageFactory` and the `AxiomSoapMessageFactory` have a `soapVersion` property, where you can inject a `SoapVersion` constant.
By default, the version is 1.1, but you can set it to 1.2:

====
[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:util="http://www.springframework.org/schema/util"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       http://www.springframework.org/schema/beans/spring-beans-2.0.xsd
       http://www.springframework.org/schema/util
       http://www.springframework.org/schema/util/spring-util-2.0.xsd">

    <bean id="messageFactory" class="org.springframework.ws.soap.saaj.SaajSoapMessageFactory">
        <property name="soapVersion">
            <util:constant static-field="org.springframework.ws.soap.SoapVersion.SOAP_12"/>
        </property>
    </bean>

</beans>
----
====

In the preceding example, we define a `SaajSoapMessageFactory` that accepts only SOAP 1.2 messages.

[WARNING]
====
Even though both versions of SOAP are quite similar in format, the 1.2 version is not backwards compatible with 1.1, because it uses a different XML namespace.
Other major differences between SOAP 1.1 and 1.2 include the different structure of a fault and the fact that `SOAPAction` HTTP headers are effectively deprecated, though they still work.

One important thing to note with SOAP version numbers (or WS-* specification version numbers in general) is that the latest version of a specification is generally not the most popular version.
For SOAP, this means that (currently) the best version to use is 1.1.
Version 1.2 might become more popular in the future, but 1.1 is currently the safest bet.
====

[[message-context]]
=== `MessageContext`

Typically, messages come in pairs: a request and a response.
A request is created on the client-side, which is sent over some transport to the server-side, where a response is generated.
This response gets sent back to the client, where it is read.

In Spring-WS, such a conversation is contained in a `MessageContext`, which has properties to get request and response messages.
On the client-side, the message context is created by the <<client-web-service-template,`WebServiceTemplate`>>.
On the server-side, the message context is read from the transport-specific input stream.
For example, in HTTP, it is read from the `HttpServletRequest`, and the response is written back to the `HttpServletResponse`.

[[transport-context]]
== `TransportContext`

One of the key properties of the SOAP protocol is that it tries to be transport-agnostic.
This is why, for instance, Spring-WS does not support mapping messages to endpoints by HTTP request URL but rather by message content.

However, it is sometimes necessary to get access to the underlying transport, either on the client or the server side.
For this, Spring-WS has the `TransportContext`.
The transport context allows access to the underlying `WebServiceConnection`, which typically is a `HttpServletConnection` on the server side or a `HttpUrlConnection` or `CommonsHttpConnection` on the client side.
For example, you can obtain the IP address of the current request in a server-side endpoint or interceptor:

====
[source,java]
----
TransportContext context = TransportContextHolder.getTransportContext();
HttpServletConnection connection = (HttpServletConnection )context.getConnection();
HttpServletRequest request = connection.getHttpServletRequest();
String ipAddress = request.getRemoteAddr();
----
====

[[xpath]]
== Handling XML With XPath

One of the best ways to handle XML is to use XPath.
Quoting <<effective-xml>>, item 35:

[quote, Elliotte Rusty Harold]
XPath is a fourth generation declarative language that allows you to specify which nodes you want to process without specifying exactly how the processor is supposed to navigate to those nodes.
XPath's data model is very well designed to support exactly what almost all developers want from XML.
For instance, it merges all adjacent text including that in CDATA sections, allows values to be calculated that skip over comments and processing instructions` and include text from child and descendant elements, and requires all external entity references to be resolved.
In practice, XPath expressions tend to be much more robust against unexpected but perhaps insignificant changes in the input document.

Spring-WS has two ways to use XPath within your application: the faster `XPathExpression` or the more flexible `XPathOperations`.

[[xpath-expression]]
=== `XPathExpression`

The `XPathExpression` is an abstraction over a compiled XPath expression, such as the Java 5 `javax.xml.xpath.XPathExpression` interface or the Jaxen `XPath` class.
To construct an expression in an application context, you can use `XPathExpressionFactoryBean`.
The following example uses this factory bean:

====
[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
          http://www.springframework.org/schema/beans/spring-beans-2.0.xsd">

    <bean id="nameExpression" class="org.springframework.xml.xpath.XPathExpressionFactoryBean">
        <property name="expression" value="/Contacts/Contact/Name"/>
    </bean>

    <bean id="myEndpoint" class="sample.MyXPathClass">
        <constructor-arg ref="nameExpression"/>
    </bean>

</beans>
----
====

The preceding expression does not use namespaces, but we could set those by using the `namespaces` property of the factory bean.
The expression can be used in the code as follows:

====
[source,java]
----
package sample;

public class MyXPathClass {

    private final XPathExpression nameExpression;

    public MyXPathClass(XPathExpression nameExpression) {
        this.nameExpression = nameExpression;
    }

    public void doXPath(Document document) {
        String name = nameExpression.evaluateAsString(document.getDocumentElement());
        System.out.println("Name: " + name);
    }

}
----
====

For a more flexible approach, you can use a `NodeMapper`, which is similar to the `RowMapper` in Spring's JDBC support.
The following example shows how to use it:

====
[source,java]
----
package sample;

public class MyXPathClass  {

   private final XPathExpression contactExpression;

   public MyXPathClass(XPathExpression contactExpression) {
      this.contactExpression = contactExpression;
   }

   public void doXPath(Document document) {
      List contacts = contactExpression.evaluate(document,
        new NodeMapper() {
           public Object mapNode(Node node, int nodeNum) throws DOMException {
              Element contactElement = (Element) node;
              Element nameElement = (Element) contactElement.getElementsByTagName("Name").item(0);
              Element phoneElement = (Element) contactElement.getElementsByTagName("Phone").item(0);
              return new Contact(nameElement.getTextContent(), phoneElement.getTextContent());
           }
        });
      PlainText Section qName; // do something with the list of Contact objects
   }
}
----
====

Similar to mapping rows in Spring JDBC's `RowMapper`, each result node is mapped by using an anonymous inner class.
In this case, we create a `Contact` object, which we use later on.

[[xpath-template]]
=== `XPathOperations`

The `XPathExpression` lets you evaluate only a single, pre-compiled expression.
A more flexible, though slower, alternative is the `XPathOperations`.
This class follows the common template pattern used throughout Spring (`JdbcTemplate`, `JmsTemplate`, and others).
The following listing shows an example:

====
[source,java,subs="verbatim,quotes"]
----
package sample;

public class MyXPathClass {

    private XPathOperations template = new Jaxp13XPathTemplate();

    public void doXPath(Source source) {
        String name = template.evaluateAsString("/Contacts/Contact/Name", request);
        _// do something with name_
    }

}
----
====

[[logging]]
== Message Logging and Tracing

When developing or debugging a web service, it can be quite useful to look at the content of a (SOAP) message when it arrives, or before it is sent.
Spring-WS offer this functionality, through the standard Commons Logging interface.

To log all server-side messages, set the `org.springframework.ws.server.MessageTracing` logger level to `DEBUG` or `TRACE`.
On the `DEBUG` level, only the payload root element is logged.
On the `TRACE` level, the entire message content is logged.
If you want to log only sent messages, use the `org.springframework.ws.server.MessageTracing.sent` logger.
Similarly, you can use `org.springframework.ws.server.MessageTracing.received` to log only received messages.

On the client-side, similar loggers exist: `org.springframework.ws.client.MessageTracing.sent` and `org.springframework.ws.client.MessageTracing.received`.

The following example of a `log4j2.properties` configuration file logs the full content of sent messages on the client side and only the payload root element for client-side received messages.
On the server-side, the payload root is logged for both sent and received messages:

====
[source]
----
appender.console.name=STDOUT
appender.console.type=Console
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%-5p [%c{3}] %m%n

rootLogger=DEBUG,STDOUT
logger.org.springframework.ws.client.MessageTracing.sent=TRACE
logger.org.springframework.ws.client.MessageTracing.received=DEBUG
logger.org.springframework.ws.server.MessageTracing=DEBUG

----
====

With this configuration, a typical output is:

====
----
TRACE [client.MessageTracing.sent] Sent request [<SOAP-ENV:Envelope xmlns:SOAP-ENV="...
DEBUG [server.MessageTracing.received] Received request [SaajSoapMessage {http://example.com}request] ...
DEBUG [server.MessageTracing.sent] Sent response [SaajSoapMessage {http://example.com}response] ...
DEBUG [client.MessageTracing.received] Received response [SaajSoapMessage {http://example.com}response] ...
----
====

[[observability]]
== Observability

Spring-WS is instrumented using the https://docs.micrometer.io/micrometer/reference/observation.html[Micrometer Observation API], so that a single instrumentation produces both metrics and tracing spans for the web service exchanges it takes part in.
Observations are disabled by default: they are only recorded once an `ObservationRegistry` is configured on the components described in this section.

NOTE: To learn more about the concepts involved, refer to the {spring-framework-docs}/integration/observability.html[Spring Framework reference documentation].

[[observability-client]]
=== Client-side Observations

Set an `ObservationRegistry` on the <<client-web-service-template,`WebServiceTemplate`>> to record an observation for each exchange it performs:

====
[source,java]
----
WebServiceTemplate template = new WebServiceTemplate(messageFactory);
template.setObservationRegistry(observationRegistry);
----
====

Each exchange is recorded under the `soap.client.requests` name, using the following key values:

[cols="1,1,3", options="header"]
|===
| Name
| Cardinality
| Description

| `exception`
| Low
| Simple class name of the exception that terminated the exchange, or `none` if the exchange completed normally.

| `fault.code`
| Low
| Fault code of the SOAP response, or `none` if the response is not a fault.

| `namespace`
| Low
| Target namespace of the operation, or `none` if it could not be determined.

| `operation.name`
| Low
| Name of the operation, as defined by `wsdl:operation name`, or `none` if it could not be determined.

| `outcome`
| Low
| `SUCCESS` for a regular response, `FAULT` for a SOAP fault, `ERROR` if an exception was thrown, or `UNKNOWN` if no response was received.

| `protocol`
| Low
| Scheme of the transport used to perform the operation, such as `http`, `jms`, or `mailto`.

| `soap.action`
| Low
| SOAP action of the operation, or `none` if the request does not define one.

| `fault.reason`
| High
| Fault reason of the SOAP response, or `none` if the response is not a fault.

| `uri`
| High
| URI of the service that the request was sent to.
|===

The namespace and the operation name are derived from the root element of the request payload, which corresponds to the `wsdl:operation` of a document-style contract.

NOTE: A SOAP fault is reported with an `outcome` of `FAULT`, even though the default `FaultMessageResolver` turns it into a `SoapFaultClientException`.
The `exception` key value lets you distinguish a fault that was turned into an exception from one that was handled by a custom `FaultMessageResolver`.

[[observability-server]]
=== Server-side Observations

Server-side observations are recorded by the transport, so the `ObservationRegistry` must be set on the component that handles the incoming connections.
For the <<message-dispatcher-servlet,`MessageDispatcherServlet`>>, this is the `WebServiceMessageReceiverHandlerAdapter`:

====
[source,java]
----
@Bean
WebServiceMessageReceiverHandlerAdapter messageReceiverHandlerAdapter(WebServiceMessageFactory messageFactory,
		ObservationRegistry observationRegistry) {
	WebServiceMessageReceiverHandlerAdapter adapter = new WebServiceMessageReceiverHandlerAdapter();
	adapter.setMessageFactory(messageFactory);
	adapter.setObservationRegistry(observationRegistry);
	return adapter;
}
----
====

The other transports expose the same property on their respective message receiver, such as `WebServiceMessageListener` for <<server-jms-transport,JMS>> and `MailMessageReceiver` for <<server-mail-transport,email>>.

Each request is recorded under the `soap.server.requests` name, using the same key values as the client, with the following differences:

* `namespace` and `operation.name` are derived from the key that the endpoint mapping used to look up the endpoint, rather than from the request payload.
They are reported as `none` for a request that could not be mapped to an endpoint.
This is deliberate: deriving them from the payload of an unmapped request would let a caller create an unbounded number of metric series by sending arbitrary payloads.
* `outcome` is `UNKNOWN` if the endpoint did not produce a response, which is the case for a one-way operation.
* `uri` is the URI that the request was received on.

[[observability-tracing]]
=== Trace Propagation

The client writes the tracing information of the current span as request headers, and the server reads it back from the request headers, for the transports that support headers.
This makes a client exchange and the server-side handling of the corresponding request part of the same trace.

Tracing information is not read on the server side for the HTTP transport, as the Servlet layer is instrumented already.
On that transport, the `soap.server.requests` observation is recorded as a child of the `http.server.requests` observation.

[[observability-conventions]]
=== Customizing Observations

The name of an observation and the key values it records are determined by an `ObservationConvention`.
To customize them, extend `DefaultSoapClientObservationConvention` or `DefaultSoapServerObservationConvention` and register your implementation using `setObservationConvention`:

====
[source,java]
----
class CustomConvention extends DefaultSoapClientObservationConvention {

	@Override
	public KeyValues getLowCardinalityKeyValues(SoapClientObservationContext context) {
		return super.getLowCardinalityKeyValues(context).and("tenant", resolveTenant(context));
	}

}
----
====

CAUTION: Only add key values with a bounded set of values to `getLowCardinalityKeyValues`, as each combination of low cardinality key values creates a separate metric series.
Values that are unbounded, such as an identifier extracted from the payload, belong to `getHighCardinalityKeyValues`, which only contributes to tracing spans.

An interceptor can also contribute metadata to the observation of the request it intercepts.
`SoapClientObservationContext.findCurrentObservationContext(MessageContext)` and its server-side counterpart return the context of the current observation, if any:

====
[source,java]
----
class OperationClientInterceptor implements ClientInterceptor {

	@Override
	public boolean handleRequest(MessageContext messageContext) {
		SoapClientObservationContext.findCurrentObservationContext(messageContext)
			.ifPresent((context) -> context.setOperationName("getCountry"));
		return true;
	}

}
----
====
