<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://springframework.org/spring-ws"
                  targetNamespace="http://springframework.org/spring-ws">
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema"
                elementFormDefault="qualified"
                targetNamespace="http://springframework.org/spring-ws">

            <element name="Element" type="string"/>

        </schema>
    </wsdl:types>
    <wsdl:message name="Message">
        <wsdl:part element="tns:string" name="Message"/>
    </wsdl:message>
    <wsdl:portType name="PortType">
        <wsdl:operation name="OneWay">
            <wsdl:input message="tns:Message"/>
        </wsdl:operation>
        <wsdl:operation name="RequestResponse">
            <wsdl:input message="tns:Message"/>
            <wsdl:output message="tns:Message"/>
            <wsdl:fault name="Fault" message="tns:Message"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="PortTypeBinding" type="tns:PortType">
        <wsdl:operation name="OneWay">
            <wsdl:input/>
        </wsdl:operation>
        <wsdl:operation name="RequestResponse">
            <wsdl:input/>
            <wsdl:output/>
            <wsdl:fault name="Fault"/>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>