//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.springframework.org/spring-ws/samples/mtom")]
public partial class Image
{
    
    private string nameField;
    
    private byte[] imageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
    public byte[] image
    {
        get
        {
            return this.imageField;
        }
        set
        {
            this.imageField = value;
        }
    }
}
namespace Spring.Ws.Samples.Mtom.Client.Wcf
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.springframework.org/spring-ws/samples/mtom", ConfigurationName="Spring.Ws.Samples.Mtom.Client.Wcf.ImageRepository")]
    public interface ImageRepository
    {
        
        // CODEGEN: Generating message contract since the operation StoreImage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void StoreImage(Spring.Ws.Samples.Mtom.Client.Wcf.StoreImageRequest request);
        
        // CODEGEN: Generating message contract since the operation LoadImage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Spring.Ws.Samples.Mtom.Client.Wcf.LoadImageResponse LoadImage(Spring.Ws.Samples.Mtom.Client.Wcf.LoadImageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoreImageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StoreImageRequest", Namespace="http://www.springframework.org/spring-ws/samples/mtom", Order=0)]
        public Image StoreImageRequest1;
        
        public StoreImageRequest()
        {
        }
        
        public StoreImageRequest(Image StoreImageRequest1)
        {
            this.StoreImageRequest1 = StoreImageRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadImageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadImageRequest", Namespace="http://www.springframework.org/spring-ws/samples/mtom", Order=0)]
        public string LoadImageRequest1;
        
        public LoadImageRequest()
        {
        }
        
        public LoadImageRequest(string LoadImageRequest1)
        {
            this.LoadImageRequest1 = LoadImageRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadImageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadImageResponse", Namespace="http://www.springframework.org/spring-ws/samples/mtom", Order=0)]
        public Image LoadImageResponse1;
        
        public LoadImageResponse()
        {
        }
        
        public LoadImageResponse(Image LoadImageResponse1)
        {
            this.LoadImageResponse1 = LoadImageResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ImageRepositoryChannel : Spring.Ws.Samples.Mtom.Client.Wcf.ImageRepository, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ImageRepositoryClient : System.ServiceModel.ClientBase<Spring.Ws.Samples.Mtom.Client.Wcf.ImageRepository>, Spring.Ws.Samples.Mtom.Client.Wcf.ImageRepository
    {
        
        public ImageRepositoryClient()
        {
        }
        
        public ImageRepositoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ImageRepositoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ImageRepositoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ImageRepositoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Spring.Ws.Samples.Mtom.Client.Wcf.ImageRepository.StoreImage(Spring.Ws.Samples.Mtom.Client.Wcf.StoreImageRequest request)
        {
            base.Channel.StoreImage(request);
        }
        
        public void StoreImage(Image StoreImageRequest1)
        {
            Spring.Ws.Samples.Mtom.Client.Wcf.StoreImageRequest inValue = new Spring.Ws.Samples.Mtom.Client.Wcf.StoreImageRequest();
            inValue.StoreImageRequest1 = StoreImageRequest1;
            ((Spring.Ws.Samples.Mtom.Client.Wcf.ImageRepository)(this)).StoreImage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Spring.Ws.Samples.Mtom.Client.Wcf.LoadImageResponse Spring.Ws.Samples.Mtom.Client.Wcf.ImageRepository.LoadImage(Spring.Ws.Samples.Mtom.Client.Wcf.LoadImageRequest request)
        {
            return base.Channel.LoadImage(request);
        }
        
        public Image LoadImage(string LoadImageRequest1)
        {
            Spring.Ws.Samples.Mtom.Client.Wcf.LoadImageRequest inValue = new Spring.Ws.Samples.Mtom.Client.Wcf.LoadImageRequest();
            inValue.LoadImageRequest1 = LoadImageRequest1;
            Spring.Ws.Samples.Mtom.Client.Wcf.LoadImageResponse retVal = ((Spring.Ws.Samples.Mtom.Client.Wcf.ImageRepository)(this)).LoadImage(inValue);
            return retVal.LoadImageResponse1;
        }
    }
}
